### ISSUE TITLE
最新工程运行，apk 奔溃

### ISSUE THREAD

**Issue by 6Weiqi** [xiaobailong24/MVVMArms#7]
`Caused by: java.lang.IllegalArgumentException: Unable to find ConfigRepository implementation
at me.xiaobailong24.mvvmarms.repository.utils.ManifestRepositoryParser.parseModule(ManifestRepositoryParser.java:53)
at me.xiaobailong24.mvvmarms.repository.utils.ManifestRepositoryParser.parse(ManifestRepositoryParser.java:37)
at me.xiaobailong24.mvvmarms.repository.RepositoryInjector.<init>(RepositoryInjector.java:28)
at me.xiaobailong24.mvvmarms.base.AppDelegate.<init>(AppDelegate.java:41)
at me.xiaobailong24.mvvmarms.base.BaseApplication.attachBaseContext(BaseApplication.java:49)`

`Caused by: java.lang.ClassNotFoundException: me.xiaobailong24.mvvmarms.weather.app.RepositoryConfiguration
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:251)
                      at java.lang.Class.forName(Class.java:216)
                      at me.xiaobailong24.mvvmarms.repository.utils.ManifestRepositoryParser.parseModule(ManifestRepositoryParser.java:51)
                      at me.xiaobailong24.mvvmarms.repository.utils.ManifestRepositoryParser.parse(ManifestRepositoryParser.java:37) 
                      at me.xiaobailong24.mvvmarms.repository.RepositoryInjector.<init>(RepositoryInjector.java:28) 
                      at me.xiaobailong24.mvvmarms.base.AppDelegate.<init>(AppDelegate.java:41) 
                      at me.xiaobailong24.mvvmarms.base.BaseApplication.attachBaseContext(BaseApplication.java:49) `

**Comment by xiaobailong24** [comment]
@6Weiqi 方便提供下测试机型和Android版本吗？

**Comment by 6Weiqi** [comment]
三星的平板，Android 4.4.2

**Comment by xiaobailong24** [comment]
@6Weiqi 可能是64K问题，demo并没做64K适配。

**Comment by 6Weiqi** [comment]
<img width="610" alt="2017-11-19 9 25 24" src="https://user-images.githubusercontent.com/19552334/32991097-3f6affac-cd70-11e7-87fe-bed2023caee7.png">

**Comment by 6Weiqi** [comment]
那应该在编译的时候就提示了吧？

**Comment by xiaobailong24** [comment]
64k是运行时检查的，可以用Android 5.0＋ 的设备先试试
